### ISSUE TITLE
covariate data problem

### ISSUE THREAD

**Issue by kolive4** [kolive4/carcharodon#3]
Covariate data not attributing to curated observations. Thinking there's an issue in the brickman_extract() function, but struggling to find where we use a time_column argument in the function.

**Comment by btupper** [comment]
I recall that this is true(ish) `st_extract(raster, points, time_column = "my_date_column")`.  We must pass `...` extra arguments through `brickman_extract(...)`. Yes?

**Comment by kolive4** [comment]
Issue with the month being a name in curated. Then extract_date column.
